
server:
  port: 8888
spring:
  application:
    name: cloud-config-server
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
        git:
          uri: https://github.com/avnerstr/dev-configuration-repo.git
          clone-submodules: true
          force-pull: true
          clone-on-start: true
          search-paths: support-configuration-repo
        overrides:
          message:
            text: this is overides text
          gracland:
            url: http://gracaland.imperva.com

